-- ============================================================
-- JanuMart - Accessories for Human.
-- Schema (idempotent: safe to run on every application start)
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    email         VARCHAR(150)  NOT NULL,
    password_hash VARCHAR(100)  NOT NULL,
    role          VARCHAR(10)   NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('BUYER', 'SELLER', 'ADMIN')),
    CONSTRAINT ck_users_email_format CHECK (email LIKE '_%@_%')
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

CREATE TABLE IF NOT EXISTS products (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    INT           NOT NULL,
    name         VARCHAR(200)  NOT NULL,
    description  VARCHAR(2000),
    price        DECIMAL(10,2) NOT NULL,
    stock_qty    INT           NOT NULL DEFAULT 0,
    category     VARCHAR(60)   NOT NULL,
    subcategory  VARCHAR(60),
    gender       VARCHAR(20),
    brand        VARCHAR(80),
    color        VARCHAR(40),
    size         VARCHAR(40),
    material     VARCHAR(80),
    image_url    VARCHAR(500),
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_products_price CHECK (price > 0),
    CONSTRAINT ck_products_stock CHECK (stock_qty >= 0),
    CONSTRAINT ck_products_gender CHECK (gender IS NULL OR gender IN ('Men', 'Women', 'Unisex'))
);

CREATE INDEX IF NOT EXISTS idx_products_seller    ON products(seller_id);
CREATE INDEX IF NOT EXISTS idx_products_category  ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_brand     ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_price     ON products(price);
CREATE INDEX IF NOT EXISTS idx_products_name      ON products(name);

CREATE TABLE IF NOT EXISTS cart_items (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INT NOT NULL,
    product_id INT NOT NULL,
    quantity   INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cart_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_cart_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
    CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT ck_cart_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_cart_user ON cart_items(user_id);

CREATE TABLE IF NOT EXISTS orders (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id       INT           NOT NULL,
    status         VARCHAR(12)   NOT NULL DEFAULT 'PENDING',
    total_amount   DECIMAL(10,2) NOT NULL,
    customer_name  VARCHAR(100)  NOT NULL,
    address        VARCHAR(300)  NOT NULL,
    city           VARCHAR(80)   NOT NULL,
    state          VARCHAR(80)   NOT NULL,
    pincode        VARCHAR(10)   NOT NULL,
    phone          VARCHAR(15)   NOT NULL,
    payment_method VARCHAR(10)   NOT NULL,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_total CHECK (total_amount >= 0),
    CONSTRAINT ck_orders_pincode CHECK (pincode LIKE '__-______' OR LENGTH(pincode) = 6),
    CONSTRAINT ck_orders_payment CHECK (payment_method IN ('UPI', 'CARD', 'COD'))
);

CREATE INDEX IF NOT EXISTS idx_orders_buyer  ON orders(buyer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

CREATE TABLE IF NOT EXISTS order_items (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT           NOT NULL,
    product_id INT           NULL,
    quantity   INT           NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_items_order   FOREIGN KEY (order_id)   REFERENCES orders(id)   ON DELETE CASCADE,
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT ck_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_items_price    CHECK (unit_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_items_order   ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_items_product ON order_items(product_id);

CREATE TABLE IF NOT EXISTS reviews (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    user_id    INT NOT NULL,
    rating     INT NOT NULL,
    comment    VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_review_user_product UNIQUE (product_id, user_id),
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
    CONSTRAINT ck_reviews_rating  CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user    ON reviews(user_id);
